spring:
  application:
    name: DatabaseSelectWithIndex

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/security?socketTimeout=2000
    hikari:
      connection-timeout: 3000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect
