spring:
  application:
    name: refactoring

  # MySQL ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}/search

  # JPA ?? ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect