spring:
  application:
    name: oauth2

  auth:
    jwt:
      secret-key: ${SECRET_KEY}
      access-token-expiry: ${ACCESS_TOKEN_EXPIRY}
      refresh-token-expiry: ${REFRESH_TOKEN_EXPIRY}

oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    token-uri: ${GOOGLE_TOKEN_URI}
    resource-uri: ${GOOGLE_RESOURCE_URI}
    scope:
     - openid
     - email
     - profile