spring:
  application:
    name: geography

  # MySQL ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}:3306/search?socketTimeout=2000
    hikari:
      connection-timeout: 3000

  # JPA ?? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    database-platform: org.hibernate.dialect.MySQLDialect
